backend:
  name: github
  repo: BrittanyIRL/lonecontrol

media_folder: static/assets
public_folder: /assets

collections:
  - label: Pages
    name: pages
    files:
      - label: "Shows Page"
        name: "shows"
        file: "content/shows.md"
        fields:
          - { name: title, label: Title }
          - { name: body, label: Body }
  - label: "Upcoming Shows"
    name: upcomingShows
    folder: "src/content/showsList"
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: venue, label: Venue }
      - { name: ticketsUrl, label: TicketsUrl }
      - { name: showPoster, label: Poster, widget: image }
      - { name: posterAlt, label: PosterAltText }
      - { name: city, label: City }
      - { name: info, label: OtherInfo }
