backend:
  name: github
  repo: BrittanyIRL/lonecontrol

media_folder: static/assets
public_folder: /assets

collections:
  - label: Pages
    name: pages
    files:
      - label: "Shows Page"
        name: "shows"
        file: "content/shows.md"
        fields:
          - { name: title, label: Title, widget: string }
          - { name: body, label: Body, widget: text }
          - { name: contact, label: Contact, widget: markdown }
          - {
              label: "Upcoming Shows",
              name: upcomingShows,
              widget: list,
              fields:
                [
                  { name: date, label: Date, widget: datetime },
                  { name: venue, label: Venue, widget: string },
                  { name: ticketsUrl, label: TicketsUrl, widget: string },
                  { name: showPoster, label: Poster, widget: image },
                  { name: posterAlt, label: PosterAltText, widget: string },
                  { name: city, label: City, widget: string },
                  { name: info, label: OtherInfo, widget: text },
                ],
            }
